

title: Hello World
email: phthang2000@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  My first website as a homework week 2 for web application dev
baseurl: ""
url: ""
twitter_username: pht
github_username:  pht

markdown: kramdown
# Build settings
theme: minima
plugins:
  - jekyll-feed

